"""Agregando columna role a users

Revision ID: 3d9b3d60d660
Revises: 
Create Date: 2026-07-09 12:30:00.000000 

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9b3d60d660'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default='CUSTOMER'))
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=False, server_default='LOCAL'))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('mfa_secret', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###